name: mhworkflow_pushdocker
on:
    workflow_dispatch:  
    #this will only run if Dockerfile changes after a push
    push:
        branches:
            - main
        paths:
            - 'Dockerfile'    

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run:
                ls
            - name: Login to Docker
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_HUB_USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

            - name: build image
              run: 
                 
                docker build . -t herreramaxi/modelbuild:latest
            - name: push image to docker hub
              run: |
                docker push herreramaxi/modelbuild:latest